version: 0.1.0
profiles:
  core-min:
    images:
      frontend: registry.example.com/observastack/frontend:v0.1.0
      bff: registry.example.com/observastack/bff:v0.1.0
      kong: docker.io/library/kong:3.6
      grafana: grafana/grafana:11.1.0
      loki: grafana/loki:3.0.0
      prometheus: prom/prometheus:v2.53.0
      tempo: grafana/tempo:2.6.0
    optional:
      keycloak: quay.io/keycloak/keycloak:26.0
      opensearch: opensearchproject/opensearch:2.17.0
      redpanda: redpandadata/redpanda:v24.2.3
  pro-default:
    extends: core-min
    enable: [keycloak, opensearch]
    ha: true
