receivers:
  otlp:
    protocols:
      grpc: {}
      http: {}
processors:
  batch:
    send_batch_size: 8192
    timeout: 5s
exporters:
  otlphttp/tempo:
    endpoint: http://tempo:3200
    tls: { insecure: true }
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/tempo]
