auth_enabled: true
server:
  http_listen_port: 3100
schema_config:
  configs:
    - from: 2025-01-01
      store: boltdb-shipper
      object_store: aws
      schema: v13
      index:
        prefix: index_
        period: 24h
storage_config:
  aws:
    s3: ${MINIO_URL}/${MINIO_BUCKET}
    s3forcepathstyle: true
    access_key_id: ${MINIO_ACCESS_KEY}
    secret_access_key: ${MINIO_SECRET_KEY}
  boltdb_shipper:
    shared_store: s3
    active_index_directory: /data/loki/index
    cache_location: /data/loki/cache
limits_config:
  retention_period: ${LOKI_RETENTION_DAYS}d
  max_label_names_per_series: 15
  max_label_value_length: 120
table_manager:
  retention_deletes_enabled: true
  retention_period: ${LOKI_RETENTION_DAYS}d
