groups:
  - name: sre-basic
    rules:
      - alert: HighCPUUsage
        expr: sum(rate(container_cpu_usage_seconds_total[5m])) by (instance) > 0.9
        for: 5m
        labels: { severity: high }
        annotations: { summary: "High CPU usage" }
