version: "3.9"
name: observastack
services:
  kong:
    image: ${KONG_IMAGE:-kong:3.6}
    ports: ["${KONG_HTTP:-8080}:8080", "${KONG_HTTPS:-8443}:8443"]
    environment:
      - KONG_DATABASE=off
    volumes:
      - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml:ro
    depends_on: [bff, frontend, grafana]
  frontend:
    image: ${FRONTEND_IMAGE:-observastack/frontend:dev}
    ports: ["3000:3000"]
  bff:
    image: ${BFF_IMAGE:-observastack/bff:dev}
    environment:
      - EDITION=${OBSERVASTACK_EDITION:-community}
    ports: ["8000:8000"]
  grafana:
    image: ${GRAFANA_IMAGE:-grafana/grafana:11.1.0}
    ports: ["${GRAFANA_PORT:-3001}:3000"]
  loki:
    image: ${LOKI_IMAGE:-grafana/loki:3.0.0}
  prometheus:
    image: ${PROM_IMAGE:-prom/prometheus:v2.53.0}
  tempo:
    image: ${TEMPO_IMAGE:-grafana/tempo:2.6.0}
  minio:
    image: quay.io/minio/minio:RELEASE.2025-01-30T00-00-00Z
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports: ["9000:9000", "9001:9001"]
