global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'observastack-monitor'
    cluster: 'docker-compose'
    prometheus: 'prometheus'
    replica: a

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']

#  - job_name: 'redis'
#    static_configs:
#      - targets: ['redis:6379']

  - job_name: 'redpanda'
    static_configs:
      - targets: ['redpanda:9644']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']

  - job_name: 'keycloak'
    static_configs:
      - targets: ['keycloak:9000']

  - job_name: 'health-monitor'
    static_configs:
      - targets: ['health-monitor:8080']  # /metrics
