server:
  http_listen_port: 3200
distributor:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}
storage:
  trace:
    backend: s3
    s3:
      endpoint: minio:9000
      bucket: ${BUCKET_TRACES}
      access_key: ${MINIO_ACCESS_KEY}
      secret_key: ${MINIO_SECRET_KEY}
      insecure: true
    block:
      version: vParquet3
compactor:
  compaction:
    block_retention: 365d
metrics_generator:
  registry:
    external_labels:
      cluster: "lab"
      tenant: "${TENANT}"
  storage:
    backend: prometheus
    remote_write:
      - url: http://prometheus-a:9090/api/v1/write
        send_exemplars: true
overrides:
  defaults:
    metrics_generator_processors: [service-graphs, span-metrics]
